name: Build, push, test and deploy Docker image

on:
  push:
    branches: [master, develop]
  release:
    types: [created]
  pull_request:
    types: [labeled, synchronize, opened, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-play:
    uses: ./.github/workflows/build-multi-arch-image.yml
    secrets: inherit
    with:
      ghcr-dev-build-image-name: 'ghcr.io/workadventure/play-dev-build'
      ghcr-image-name: 'ghcr.io/workadventure/play'
      dockerio-image-name: 'thecodingmachine/workadventure-play'
      # FIXME: Final build should only build on master or tags
      final_build: ${{ github.event_name == 'push' || github.event_name == 'release' || (github.event_name == 'pull_request' && (contains(github.event.pull_request.labels.*.name, 'deploy') || contains(github.event.pull_request.labels.*.name, 'deploy-with-livekit-saas') || contains(github.event.pull_request.labels.*.name, 'build') || contains(github.event.pull_request.labels.*.name, 'linked_to_saas_branch'))) }}
      dockerfile: play/Dockerfile
      short_name: play
      # sentry_project: play
      # We only push to the registry if we are in the WorkAdventure organization. Otherwise, we will use artifacts because GITHUB_TOKEN from a public fork have no write access, even to the local user repository.
      push-to-registry: ${{ (github.event_name == 'pull_request' && github.event.pull_request.head.repo.owner.login == 'workadventure') || (github.event_name != 'pull_request' && github.repository_owner == 'workadventure') }}
      context: ./
      # Fast build for PRs that do NOT have the 'build-legacy-browsers' label
      fast_build: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'build-legacy-browsers') == false }}

      # docker
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: rlespinasse/github-slug-action@4.2.3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: mconf/workadventure-play

      - name: Build and push
        uses: docker/build-push-action@v3
        if: ${{ github.event_name == 'push' || github.event_name == 'release' || github.event_name == 'pull_request' && (contains(github.event.pull_request.labels.*.name, 'deploy') || contains(github.event.pull_request.labels.*.name, 'build')) }}
        with:
          context: .
          file: play/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: mconf/workadventure-play:${{ github.event_name == 'pull_request' && env.GITHUB_HEAD_REF_SLUG || env.GITHUB_REF_SLUG }}
          cache-from: |
            type=registry,ref=mconf/workadventure-play:${{ github.event_name == 'pull_request' && env.GITHUB_HEAD_REF_SLUG || env.GITHUB_REF_SLUG }}
            type=registry,ref=mconf/workadventure-play:develop
          cache-to: type=inline
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            "SENTRY_URL=${{ secrets.SENTRY_URL }}"
            "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}"
            "SENTRY_ORG=${{ secrets.SENTRY_ORG }}"
            "SENTRY_PROJECT=play"
            "SENTRY_ENVIRONMENT=${{ github.event_name == 'release' && 'production' || env.GITHUB_REF_NAME == 'master' && 'staging' || 'testing' }}"
            "SENTRY_RELEASE=${{ github.event_name == 'release' && env.GITHUB_REF_NAME || format('{0}@{1}', env.GITHUB_REF_NAME, env.GITHUB_SHA) }}"

  build-back:
    uses: ./.github/workflows/build-multi-arch-image.yml
    secrets: inherit
    with:
      ghcr-dev-build-image-name: 'ghcr.io/workadventure/back-dev-build'
      ghcr-image-name: 'ghcr.io/workadventure/back'
      dockerio-image-name: 'thecodingmachine/workadventure-back'
      final_build: ${{ github.event_name == 'push' || github.event_name == 'release' || github.event_name == 'pull_request' && (contains(github.event.pull_request.labels.*.name, 'deploy') || contains(github.event.pull_request.labels.*.name, 'deploy-with-livekit-saas') || contains(github.event.pull_request.labels.*.name, 'build') || contains(github.event.pull_request.labels.*.name, 'linked_to_saas_branch')) }}
      dockerfile: back/Dockerfile
      short_name: back
      sentry_project: back
      # We only push to the registry if we are in the WorkAdventure organization. Otherwise, we will use artifacts because GITHUB_TOKEN from a public fork have no write access, even to the local user repository.
      push-to-registry: ${{ (github.event_name == 'pull_request' && github.event.pull_request.head.repo.owner.login == 'workadventure') || (github.event_name != 'pull_request' && github.repository_owner == 'workadventure') }}
      context: ./

  build-uploader:
    uses: ./.github/workflows/build-multi-arch-image.yml
    secrets: inherit
    with:
      ghcr-dev-build-image-name: 'ghcr.io/workadventure/uploader-dev-build'
      ghcr-image-name: 'ghcr.io/workadventure/uploader'
      dockerio-image-name: 'thecodingmachine/workadventure-uploader'
      final_build: ${{ github.event_name == 'push' || github.event_name == 'release' || github.event_name == 'pull_request' && (contains(github.event.pull_request.labels.*.name, 'deploy') || contains(github.event.pull_request.labels.*.name, 'deploy-with-livekit-saas') || contains(github.event.pull_request.labels.*.name, 'build') || contains(github.event.pull_request.labels.*.name, 'linked_to_saas_branch')) }}
      dockerfile: uploader/Dockerfile
      short_name: uploader
      sentry_project: uploader
      # We only push to the registry if we are in the WorkAdventure organization. Otherwise, we will use artifacts because GITHUB_TOKEN from a public fork have no write access, even to the local user repository.
      push-to-registry: ${{ (github.event_name == 'pull_request' && github.event.pull_request.head.repo.owner.login == 'workadventure') || (github.event_name != 'pull_request' && github.repository_owner == 'workadventure') }}
      context: ./

  build-maps:
    uses: ./.github/workflows/build-multi-arch-image.yml
    secrets: inherit
    with:
      ghcr-dev-build-image-name: 'ghcr.io/workadventure/maps-dev-build'
      ghcr-image-name: 'ghcr.io/workadventure/maps'
      dockerio-image-name: 'thecodingmachine/workadventure-maps'
      final_build: ${{ github.event_name == 'push' || github.event_name == 'release' || github.event_name == 'pull_request' && (contains(github.event.pull_request.labels.*.name, 'deploy') || contains(github.event.pull_request.labels.*.name, 'deploy-with-livekit-saas') || contains(github.event.pull_request.labels.*.name, 'build') || contains(github.event.pull_request.labels.*.name, 'linked_to_saas_branch')) }}
      dockerfile: maps/Dockerfile
      short_name: maps
      sentry_project: maps
      # We only push to the registry if we are in the WorkAdventure organization. Otherwise, we will use artifacts because GITHUB_TOKEN from a public fork have no write access, even to the local user repository.
      push-to-registry: ${{ (github.event_name == 'pull_request' && github.event.pull_request.head.repo.owner.login == 'workadventure') || (github.event_name != 'pull_request' && github.repository_owner == 'workadventure') }}
      context: ./maps

  build-map-storage:
    uses: ./.github/workflows/build-multi-arch-image.yml
    secrets: inherit
    with:
      ghcr-dev-build-image-name: 'ghcr.io/workadventure/map-storage-dev-build'
      ghcr-image-name: 'ghcr.io/workadventure/map-storage'
      dockerio-image-name: 'thecodingmachine/workadventure-map-storage'
      final_build: ${{ github.event_name == 'push' || github.event_name == 'release' || github.event_name == 'pull_request' && (contains(github.event.pull_request.labels.*.name, 'deploy') || contains(github.event.pull_request.labels.*.name, 'deploy-with-livekit-saas') || contains(github.event.pull_request.labels.*.name, 'build') || contains(github.event.pull_request.labels.*.name, 'linked_to_saas_branch')) }}
      dockerfile: map-storage/Dockerfile
      short_name: map-storage
      sentry_project: map-storage
      # We only push to the registry if we are in the WorkAdventure organization. Otherwise, we will use artifacts because GITHUB_TOKEN from a public fork have no write access, even to the local user repository.
      push-to-registry: ${{ (github.event_name == 'pull_request' && github.event.pull_request.head.repo.owner.login == 'workadventure') || (github.event_name != 'pull_request' && github.repository_owner == 'workadventure') }}
      context: ./

  push-to-sentry:
    runs-on: ubuntu-latest
    #if: ${{ github.event_name == 'push' || github.event_name == 'release' || github.event_name == 'pull_request' && (contains(github.event.pull_request.labels.*.name, 'deploy') || contains(github.event.pull_request.labels.*.name, 'build')) }}
    if: ${{ github.event_name == 'release' || (github.event_name == 'push' && github.ref == 'refs/heads/master') }}
    needs:
#      - build-play
      - build-back
      - build-map-storage
    steps:
#      - name: Sentry push play source maps
#        continue-on-error: true
#        env:
#          SENTRY_URL: ${{ secrets.SENTRY_URL }}
#          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
#          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
#          SENTRY_PROJECT: pusher
#          SENTRY_ENVIRONMENT: ${{ github.event_name == 'release' && 'production' || env.GITHUB_REF_NAME == 'master' && 'staging' || null }}
#          SENTRY_RELEASE: ${{ github.event_name == 'release' && env.GITHUB_REF_NAME || format('{0}@{1}', env.GITHUB_REF_NAME, env.GITHUB_SHA) }}
#        run: |
#          docker run --rm \
#            --user 0       \
#            -e SENTRY_URL \
#            -e SENTRY_AUTH_TOKEN \
#            -e SENTRY_ORG \
#            -e SENTRY_PROJECT \
#            -e SENTRY_RELEASE \
#            -e SENTRY_ENVIRONMENT \
#            ghcr.io/workadventure/play-dev-build:amd64-${{ github.sha }} \
#            /bin/sh -c 'npm install --dev && npm run push-sentry-sourcemaps'

      # docker
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: rlespinasse/github-slug-action@4.2.3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: mconf/workadventure-back

      - name: Replace version string
        run: |
          if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            sed -i "s/dev/${GITHUB_REF_NAME}/" back/src/Services/version.ts
          fi

      - name: Build and push
        uses: docker/build-push-action@v3
        if: ${{ github.event_name == 'push' || github.event_name == 'release' || github.event_name == 'pull_request' && (contains(github.event.pull_request.labels.*.name, 'deploy') || contains(github.event.pull_request.labels.*.name, 'build')) }}
        with:
          context: .
          file: back/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: mconf/workadventure-back:${{ github.event_name == 'pull_request' && env.GITHUB_HEAD_REF_SLUG || env.GITHUB_REF_SLUG }}
          cache-from: |
            type=registry,ref=mconf/workadventure-back:${{ github.event_name == 'pull_request' && env.GITHUB_HEAD_REF_SLUG || env.GITHUB_REF_SLUG }}
            type=registry,ref=mconf/workadventure-back:develop
          cache-to: type=inline
          labels: ${{ steps.meta.outputs.labels }}

  build-uploader:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: rlespinasse/github-slug-action@4.2.3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: mconf/workadventure-uploader

      - name: Build and push
        uses: docker/build-push-action@v3
        if: ${{ github.event_name == 'push' || github.event_name == 'release' || github.event_name == 'pull_request' && (contains(github.event.pull_request.labels.*.name, 'deploy') || contains(github.event.pull_request.labels.*.name, 'build')) }}
        with:
          file: uploader/Dockerfile
          push: true
          tags: mconf/workadventure-uploader:${{ github.event_name == 'pull_request' && env.GITHUB_HEAD_REF_SLUG || env.GITHUB_REF_SLUG }}
          cache-from: |
            type=registry,ref=mconf/workadventure-uploader:${{ github.event_name == 'pull_request' && env.GITHUB_HEAD_REF_SLUG || env.GITHUB_REF_SLUG }}
            type=registry,ref=mconf/workadventure-uploader:develop
          cache-to: type=inline
          labels: ${{ steps.meta.outputs.labels }}

  build-maps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: rlespinasse/github-slug-action@4.2.3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: mconf/workadventure-maps

      - name: Build and push
        uses: docker/build-push-action@v3
        if: ${{ github.event_name == 'push' || github.event_name == 'release' || github.event_name == 'pull_request' && (contains(github.event.pull_request.labels.*.name, 'deploy') || contains(github.event.pull_request.labels.*.name, 'build')) }}
        with:
          context: maps/
          file: maps/Dockerfile
          push: true
          tags: mconf/workadventure-maps:${{ github.event_name == 'pull_request' && env.GITHUB_HEAD_REF_SLUG || env.GITHUB_REF_SLUG }}
          cache-from: |
            type=registry,ref=mconf/workadventure-maps:${{ github.event_name == 'pull_request' && env.GITHUB_HEAD_REF_SLUG || env.GITHUB_REF_SLUG }}
            type=registry,ref=mconf/workadventure-maps:develop
          cache-to: type=inline
          labels: ${{ steps.meta.outputs.labels }}

  build-map-storage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # docker
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: rlespinasse/github-slug-action@4.2.3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: mconf/workadventure-map-storage

      - name: Build and push
        uses: docker/build-push-action@v3
        if: ${{ github.event_name == 'push' || github.event_name == 'release' || github.event_name == 'pull_request' && (contains(github.event.pull_request.labels.*.name, 'deploy') || contains(github.event.pull_request.labels.*.name, 'build')) }}
        with:
          context: .
          file: map-storage/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: mconf/workadventure-map-storage:${{ github.event_name == 'pull_request' && env.GITHUB_HEAD_REF_SLUG || env.GITHUB_REF_SLUG }}
          cache-from: |
            type=registry,ref=mconf/workadventure-map-storage:${{ github.event_name == 'pull_request' && env.GITHUB_HEAD_REF_SLUG || env.GITHUB_REF_SLUG }}
            type=registry,ref=mconf/workadventure-map-storage:develop
          cache-to: type=inline
          labels: ${{ steps.meta.outputs.labels }}
